services:
  auth-service:
    image: ghcr.io/element-hq/lk-jwt-service:latest-ci
    environment:
      - LK_JWT_PORT=8080
      - LIVEKIT_URL=wss://test.im.avato.cc/livekit/sfu
      - LIVEKIT_KEY=devkey
      - LIVEKIT_SECRET=secret
      # If the configured homeserver runs on localhost, it'll probably be using
      # a self-signed certificate
      - LIVEKIT_INSECURE_SKIP_VERIFY_TLS=YES_I_KNOW_WHAT_I_AM_DOING
    deploy:
      restart_policy:
        condition: on-failure
    network_mode: host

  livekit:
    image: livekit/livekit-server:latest
    command: --dev --config /etc/livekit.yaml
    restart: unless-stopped
    volumes:
      - ./dev_livekit.yaml:/etc/livekit.yaml:Z
    network_mode: host

  avatochat-server:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    environment:
      CONDUWUIT_SERVER_NAME: test.im.avato.cc # EDIT THIS
      CONDUWUIT_DATABASE_PATH: /var/lib/conduwuit
      CONDUWUIT_PORT: 8008
      CONDUWUIT_MAX_REQUEST_SIZE: 20000000 # in bytes, ~20 MB
      CONDUWUIT_ALLOW_REGISTRATION: 'true'
      # CONDUWUIT_REGISTRATION_TOKEN: 'TOKEN' # A registration token is required when registration is allowed.
      CONDUWUIT_YES_I_AM_VERY_VERY_SURE_I_WANT_AN_OPEN_REGISTRATION_SERVER_PRONE_TO_ABUSE: 'true'
      CONDUWUIT_ALLOW_FEDERATION: 'true'
      CONDUWUIT_ALLOW_CHECK_FOR_UPDATES: 'true'
      CONDUWUIT_TRUSTED_SERVERS: '["matrix.org"]'
      #CONDUWUIT_LOG: warn,state_res=warn
      CONDUWUIT_ADDRESS: 0.0.0.0
      CONDUWUIT_WELL_KNOWN: |
        {
        client=https://test.im.avato.cc,
        livekit_service_url=https://test.im.avato.cc/livekit/jwt
        }
    network_mode: host

  nginx:
    image: nginx:latest
    volumes:
      - ./dev_nginx.conf:/etc/nginx/conf.d/default.conf:Z
      - ./dev_crt.pem:/root/ssl/crt.pem:Z
      - ./dev_key.pem:/root/ssl/key.pem:Z
    depends_on:
      - avatochat-server
    network_mode: host
